export const tileWidth = 40;
export const tileHeight = tileWidth;
export const mapWidth = 20;
export const mapHeight = 20;
export const playerWidth = 30;
export const playerHeight = 30;
// export const playerWidth = tileWidth;
// export const playerHeight = tileHeight;
export const defaultSpeed = 1;
